openapi: 3.0.0
info:
  title: Portfolio API
  version: '0.1'
servers:
  - url: 'http://localhost:5000/mock/api'
paths:
  /portfolios:
    get:
      operationId: getListOfAllPortfolios
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PortfolioSummaries'
components:
  schemas:
    AccountType:
      type: string
      enum:
        - TRADING
        - ISA
    PortfolioSummary:
      example:
        portfolioName: Interactive Investor - ISA
        accountType: ISA
        totalValue: 40000
        lastUpdated: '2020-06-28T16:53:20.000Z'
      type: object
      required:
        - portfolioName
        - accountType
        - totalValue
        - lastUpdated
      properties:
        portfolioName:
          type: string
        accountType:
          $ref: '#/components/schemas/AccountType'
        totalValue:
          type: number
          format: int
        lastUpdated:
          type: string
          format: date-time
    PortfolioSummaries:
      description: A collection of portfolio summaries
      type: object
      required: 
        - portfolios
        - size
        - currency
      properties:
        size:
          type: number
          format: int
        currency:
          type: string
        portfolios:
          type: array
          maxItems: 10
          items:
            $ref: '#/components/schemas/PortfolioSummary'

